In [1]:
(5,7)

(5, 7)

In [2]:
5,7

(5, 7)

In [3]:
(5,)

(5,)

In [4]:
list_a=[1,3,5,7,9]
list_b=[3,5,6,7,9]
list_a + list_b

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]

In [5]:
import numpy as np
array_a=np.array([1,3,5,7,9])
array_b=np.array([3,5,6,7,9])
type(array_a)
array_a + array_b

array([ 4,  8, 11, 14, 18])

In [6]:
import numpy as np

l = [[1,2,3],[2,3,4]]
array = np.array(l)
array.ndim,array.shape,array.size,array.dtype


(2, (2, 3), 6, dtype('int64'))

In [7]:
import numpy as np
np.random.rand(10,5)


array([[0.64270395, 0.83501504, 0.19791311, 0.09073717, 0.29358316],
       [0.97889398, 0.59294489, 0.38688277, 0.62805525, 0.35823575],
       [0.10270612, 0.09700661, 0.91206212, 0.98028276, 0.15135383],
       [0.93928664, 0.37712767, 0.96180703, 0.78286122, 0.56049424],
       [0.77446151, 0.16592736, 0.15934013, 0.16884747, 0.2858122 ],
       [0.69310308, 0.55111284, 0.43803672, 0.5354342 , 0.75889019],
       [0.39333929, 0.97679463, 0.05884823, 0.49098537, 0.13702111],
       [0.53035819, 0.24862497, 0.48950491, 0.49521178, 0.98358901],
       [0.05426695, 0.87504306, 0.27790547, 0.70082688, 0.32406319],
       [0.94825344, 0.88913399, 0.82320018, 0.7684423 , 0.83432244]])

In [10]:
#50個學生,每個學生有5個分數(50,5)
scores = np.random.randint(50,101,size=(50,5))
scores

array([[ 68,  66,  69,  73,  81],
       [ 57,  91,  76,  89,  81],
       [ 57,  70,  51,  79,  92],
       [ 86,  53,  62,  93,  84],
       [ 76,  70,  72,  81,  59],
       [ 66,  86,  93,  97,  78],
       [ 67,  71,  95,  73,  77],
       [ 86,  84,  93,  63,  88],
       [ 68,  76,  87,  72,  73],
       [ 54,  74, 100,  70,  53],
       [ 61,  92,  73,  94,  92],
       [ 88,  51,  55,  57,  92],
       [ 97,  58,  69,  66,  69],
       [ 77,  52,  53,  91,  55],
       [ 66, 100,  95,  87,  59],
       [ 98,  65,  72, 100,  62],
       [ 79,  84,  70,  75,  60],
       [ 52,  66,  61,  91,  96],
       [ 59,  54,  87,  71,  59],
       [ 95,  56, 100,  96,  83],
       [ 90,  80,  92,  76,  56],
       [ 92,  58,  57,  84,  78],
       [ 65,  84,  93,  68,  66],
       [ 81,  59,  50,  51, 100],
       [ 82,  80,  56,  69,  56],
       [ 70,  80,  51,  61,  78],
       [ 86,  71,  85,  95,  81],
       [ 78,  66,  64,  53,  74],
       [ 76,  93,  71,  76,  66],
       [ 88,  

In [11]:
#第一個學生
scores[0,:]
#前五個學生
scores[:5,:]
#最後五個學生
scores[-5:,:]

array([[95, 76, 69, 53, 87],
       [75, 74, 84, 91, 91],
       [75, 82, 75, 89, 61],
       [79, 55, 70, 72, 73],
       [82, 97, 94, 89, 88]])

In [12]:
#全班第一科的分數
scores[:,0]


array([68, 57, 57, 86, 76, 66, 67, 86, 68, 54, 61, 88, 97, 77, 66, 98, 79,
       52, 59, 95, 90, 92, 65, 81, 82, 70, 86, 78, 76, 88, 82, 65, 91, 52,
       59, 70, 79, 64, 54, 79, 74, 64, 50, 87, 55, 95, 75, 75, 79, 82])

In [13]:
#全班第二科的分數
scores[:,1]


array([ 66,  91,  70,  53,  70,  86,  71,  84,  76,  74,  92,  51,  58,
        52, 100,  65,  84,  66,  54,  56,  80,  58,  84,  59,  80,  80,
        71,  66,  93,  64,  98,  61,  79,  88,  74, 100,  62,  70,  53,
        65,  76,  98,  78,  50,  97,  76,  74,  82,  55,  97])

In [16]:
#每位學生的總分
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]
total

array([357, 394, 349, 378, 358, 420, 383, 414, 376, 351, 412, 343, 359,
       328, 407, 397, 368, 366, 330, 430, 394, 369, 376, 341, 343, 340,
       418, 335, 382, 401, 445, 351, 398, 376, 349, 435, 374, 320, 349,
       377, 381, 369, 343, 393, 344, 380, 415, 382, 349, 450])

In [17]:
#使用統計的方法
#每個學生總分
np.sum(scores,axis=1)

array([357, 394, 349, 378, 358, 420, 383, 414, 376, 351, 412, 343, 359,
       328, 407, 397, 368, 366, 330, 430, 394, 369, 376, 341, 343, 340,
       418, 335, 382, 401, 445, 351, 398, 376, 349, 435, 374, 320, 349,
       377, 381, 369, 343, 393, 344, 380, 415, 382, 349, 450])

In [18]:
#每個學生平均
np.mean(scores,axis=1)

array([71.4, 78.8, 69.8, 75.6, 71.6, 84. , 76.6, 82.8, 75.2, 70.2, 82.4,
       68.6, 71.8, 65.6, 81.4, 79.4, 73.6, 73.2, 66. , 86. , 78.8, 73.8,
       75.2, 68.2, 68.6, 68. , 83.6, 67. , 76.4, 80.2, 89. , 70.2, 79.6,
       75.2, 69.8, 87. , 74.8, 64. , 69.8, 75.4, 76.2, 73.8, 68.6, 78.6,
       68.8, 76. , 83. , 76.4, 69.8, 90. ])